class Rates {
  Rates({
    required this.usd,
    required this.cad,
    required this.gbp,
    required this.sek,
    required this.nok,
    required this.ils,
    required this.dkk,
    required this.aud,
    required this.kwd,
    required this.rub,
    required this.inr,
    required this.bnd,
    required this.eur,
    required this.zar,
    required this.npr,
    required this.chf,
    required this.cny,
    required this.thb,
    required this.pkr,
    required this.kes,
    required this.egp,
    required this.bdt,
    required this.lak,
    required this.sar,
    required this.idr,
    required this.khr,
    required this.sgd,
    required this.lkr,
    required this.nzd,
    required this.czk,
    required this.jpy,
    required this.vnd,
    required this.php,
    required this.krw,
    required this.hkd,
    required this.brl,
    required this.rsd,
    required this.myr,
  });

  String usd;
  String cad;
  String gbp;
  String sek;
  String nok;
  String ils;
  String dkk;
  String aud;
  String kwd;
  String rub;
  String inr;
  String bnd;
  String eur;
  String zar;
  String npr;
  String chf;
  String cny;
  String thb;
  String pkr;
  String kes;
  String egp;
  String bdt;
  String lak;
  String sar;
  String idr;
  String khr;
  String sgd;
  String lkr;
  String nzd;
  String czk;
  String jpy;
  String vnd;
  String php;
  String krw;
  String hkd;
  String brl;
  String rsd;
  String myr;

  factory Rates.fromJson(Map<String, dynamic> json) => Rates(
        usd: json["USD"],
        cad: json["CAD"],
        gbp: json["GBP"],
        sek: json["SEK"],
        nok: json["NOK"],
        ils: json["ILS"],
        dkk: json["DKK"],
        aud: json["AUD"],
        kwd: json["KWD"],
        rub: json["RUB"],
        inr: json["INR"],
        bnd: json["BND"],
        eur: json["EUR"],
        zar: json["ZAR"],
        npr: json["NPR"],
        chf: json["CHF"],
        cny: json["CNY"],
        thb: json["THB"],
        pkr: json["PKR"],
        kes: json["KES"],
        egp: json["EGP"],
        bdt: json["BDT"],
        lak: json["LAK"],
        sar: json["SAR"],
        idr: json["IDR"],
        khr: json["KHR"],
        sgd: json["SGD"],
        lkr: json["LKR"],
        nzd: json["NZD"],
        czk: json["CZK"],
        jpy: json["JPY"],
        vnd: json["VND"],
        php: json["PHP"],
        krw: json["KRW"],
        hkd: json["HKD"],
        brl: json["BRL"],
        rsd: json["RSD"],
        myr: json["MYR"],
      );

  Map<String, dynamic> toJson() => {
        "USD": usd,
        "CAD": cad,
        "GBP": gbp,
        "SEK": sek,
        "NOK": nok,
        "ILS": ils,
        "DKK": dkk,
        "AUD": aud,
        "KWD": kwd,
        "RUB": rub,
        "INR": inr,
        "BND": bnd,
        "EUR": eur,
        "ZAR": zar,
        "NPR": npr,
        "CHF": chf,
        "CNY": cny,
        "THB": thb,
        "PKR": pkr,
        "KES": kes,
        "EGP": egp,
        "BDT": bdt,
        "LAK": lak,
        "SAR": sar,
        "IDR": idr,
        "KHR": khr,
        "SGD": sgd,
        "LKR": lkr,
        "NZD": nzd,
        "CZK": czk,
        "JPY": jpy,
        "VND": vnd,
        "PHP": php,
        "KRW": krw,
        "HKD": hkd,
        "BRL": brl,
        "RSD": rsd,
        "MYR": myr,
      };
}
